library graphview;

import 'dart:async';
import 'dart:collection';
import 'dart:convert';
import 'dart:math';

import 'package:collection/collection.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';

part 'Algorithm.dart';
part 'Graph.dart';
part 'config/NodeDraggingConfiguration.dart';
part 'controller/GraphViewController.dart';
part 'delegate/GraphChildDelegate.dart';
part 'delegate/GraphChildManager.dart';
part 'edgerenderer/ArrowEdgeRenderer.dart';
part 'edgerenderer/EdgeRenderer.dart';
part 'edgerenderer/CurvedEdgeRenderer.dart';
part 'edgerenderer/AnimatedEdgeRenderer.dart';
part 'edgerenderer/AdaptiveEdgeRenderer.dart';
part 'edgerenderer/OrthogonalEdgeRenderer.dart';
part 'edgerenderer/routing/VectorUtils.dart';
part 'edgerenderer/routing/EdgeRoutingConfig.dart';
part 'edgerenderer/routing/EdgeRepulsionSolver.dart';
part 'forcedirected/BarnesHutQuadtree.dart';
part 'forcedirected/FruchtermanReingoldAlgorithm.dart';
part 'forcedirected/FruchtermanReingoldConfiguration.dart';
part 'layered/LayeredAlgorithmBase.dart';
part 'layered/EiglspergerAlgorithm.dart';
part 'layered/EiglspergerEdgeData.dart';
part 'layered/EiglspergerEdgeRenderer.dart';
part 'layered/EiglspergerNodeData.dart';
part 'layered/SugiyamaAlgorithm.dart';
part 'layered/SugiyamaConfiguration.dart';
part 'layered/SugiyamaEdgeData.dart';
part 'layered/SugiyamaEdgeRenderer.dart';
part 'layered/SugiyamaNodeData.dart';
part 'mindmap/MindMapAlgorithm.dart';
part 'mindmap/MindmapEdgeRenderer.dart';
part 'painter/EdgeRender.dart';
part 'painter/GraphViewCustomPainter.dart';
part 'renderobject/GraphViewElement.dart';
part 'renderobject/GraphViewWidget.dart';
part 'renderobject/NodeBoxData.dart';
part 'renderobject/RenderCustomLayoutBox.dart';
part 'tree/BaloonLayoutAlgorithm.dart';
part 'tree/BuchheimWalkerAlgorithm.dart';
part 'tree/BuchheimWalkerConfiguration.dart';
part 'tree/BuchheimWalkerNodeData.dart';
part 'tree/CircleLayoutAlgorithm.dart';
part 'tree/RadialTreeLayoutAlgorithm.dart';
part 'tree/TidierTreeLayoutAlgorithm.dart';
part 'tree/TreeEdgeRenderer.dart';
part 'util/orientation_utils.dart';
part 'widget/GraphView.dart';

typedef NodeWidgetBuilder = Widget Function(Node node);
typedef EdgeWidgetBuilder = Widget Function(Edge edge);
typedef OnNodeDragStart = void Function(Node node);
typedef OnNodeDragUpdate = void Function(Node node, Offset position);
typedef OnNodeDragEnd = void Function(Node node, Offset finalPosition);
